# Generated by Django 3.2.7 on 2021-10-06 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0006_auto_20211005_2228'),
        ('Usuarios', '0001_initial'),
        ('Renta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='idReserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Renta.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idLugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalogo.lugar'),
        ),
    ]
