# Generated by Django 3.2.7 on 2021-10-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renta', '0002_auto_20211005_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_fin_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_ini_reserva',
            field=models.DateField(),
        ),
    ]
